package server

import (
	"encoding/json"
	"errors"
	"mime"
	"net/http"
	"strings"

	"github.com/datcal/ambar/internal/palette"
)

// handlePaletteExport serves an asset's extracted palette in one interchange
// format (§8 "Copy and export"): /assets/{id}/palette/{format}.
//
// The palette is derived data, already in the index, so this handler never touches
// the library — no safepath, no original bytes. Everything is served as an
// attachment: a .css or .tres rendered inline from the app origin would be content
// the browser could act on, and §11's serving rules apply to generated bytes too.
func (s *Server) handlePaletteExport(w http.ResponseWriter, r *http.Request) {
	asset, ok := s.lookupAsset(w, r)
	if !ok {
		return
	}

	format := r.PathValue("format")

	if !asset.HasPalette() {
		http.Error(w, "no palette was extracted for this asset", http.StatusNotFound)
		return
	}

	var swatches []palette.Swatch
	if err := json.Unmarshal([]byte(asset.PaletteJSON), &swatches); err != nil {
		s.log.ErrorContext(r.Context(), "stored palette is not valid JSON",
			"asset_id", asset.ID, "error", err)
		http.Error(w, "the stored palette could not be read", http.StatusInternalServerError)
		return
	}

	p := palette.Palette{Kind: asset.PaletteKind, Swatches: swatches}
	data, err := palette.Export(p, paletteName(asset.PackName, asset.Filename), format)
	if errors.Is(err, palette.ErrUnknownFormat) {
		http.Error(w, "unknown palette format", http.StatusNotFound)
		return
	}
	if err != nil {
		s.log.ErrorContext(r.Context(), "palette export failed",
			"asset_id", asset.ID, "format", format, "error", err)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", palette.ContentType(format))
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Content-Disposition",
		mime.FormatMediaType("attachment", map[string]string{
			"filename": exportFilename(asset.Filename, format),
		}))
	w.Write(data) //nolint:errcheck // nothing useful to do if the client hung up
}

// paletteName labels the palette inside formats that carry a name (GIMP,
// GDScript), e.g. "kenney-space — ship.png".
func paletteName(packName, filename string) string {
	if packName == "" {
		return filename
	}
	return packName + " — " + filename
}

// exportFilename turns "ship.png" into "ship-palette.gpl": the asset's base name,
// its extension replaced by a "-palette" tag and the export format.
func exportFilename(filename, format string) string {
	base := filename
	if i := strings.LastIndexByte(base, '.'); i > 0 {
		base = base[:i]
	}
	return base + "-palette." + format
}
